  
# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  java-image:
    working_directory: /root/repo
    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m
    docker:
      - image: ${JFROG_DOCKER_HOST}/tmc-private-images/java17
        auth:
          username: ${JFROG_USERNAME}
          password: ${JFROG_TOKEN}
  snapshot-publisher-image:
    working_directory: /root/repo
    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m
    docker:
      - image: ${JFROG_DOCKER_HOST}/tmc-private-images/java
        auth:
          username: ${JFROG_USERNAME}
          password: ${JFROG_TOKEN}
  gitleaks-image:
    working_directory: /root/repo
    docker:
      - image: ${JFROG_DOCKER_HOST}/tmc-private-images/gitleaks
        auth:
          username: ${JFROG_USERNAME}
          password: ${JFROG_TOKEN}

jobs:
  scan_secrets:
    executor: gitleaks-image
    steps:
      - checkout
      - persist_to_workspace:
          root: /root
          paths:
            - repo
      - run: gitleaks
  build:
    executor: java-image
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Cleanup dependencies
          command: mvn clean
      - restore_cache:
          keys:
            - tmc-oss-sdk-common-{{ checksum "pom.xml" }}-maven
      - run:
          name: Build tmc-oss-sdk-common
          command: |
            mvn dependency:go-offline -DskipTests install -Pford-supplier-jfrog-artifactory-tmc-oss
      - persist_to_workspace:
          root: /root
          paths:
            - .m2
      - save_cache:
          paths:
            - ~/.m2
          key: tmc-oss-sdk-common-{{ checksum "pom.xml" }}-maven
  test:
    executor: java-image
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Run unit tests
          command: mvn verify -Pford-supplier-jfrog-artifactory-tmc-oss
      - run:
          name: Save test results
          command: |
            mkdir -p test-output
            cp -fr target/site/jacoco test-output
          when: always
      - store_test_results:
          path: test-output
      - store_artifacts:
          path: test-output
      - persist_to_workspace:
          root: /root
          paths:
            - repo/target
  #publish artifact to OSS repo
  publish-public:
    executor: java-image
    working_directory: /root/repo
    steps:
      - attach_workspace:
          at: /root
      - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - run:
          name: Publish to au-tmc-oss and run revapi
          command: |
            mvn deploy \
              -Pcloudsmith-autonomic-au-tmc-oss \
              -DaltDeploymentRepository="cloudsmith-autonomic-au-tmc-oss::https://maven.cloudsmith.io/autonomic/au-tmc-oss" \
              -DskipTests
  publish-public-jfrog:
    executor: snapshot-publisher-image
    working_directory: /root/repo
    steps:
      - attach_workspace:
          at: /root
      - run: |
          mvn versions:use-dep-version -Dincludes=com.autonomic.tmc:tmc-oss-parent -DdepVersion=LATEST-SNAPSHOT -DforceVersion=true
          mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - run:
          name: Publish to tmc-oss and run revapi
          command: |
            mvn deploy \
              -Pford-supplier-jfrog-artifactory-tmc-oss \
              -DaltDeploymentRepository="ford-supplier-jfrog-artifactory-tmc-oss::${JFROG_URL}/${JFROG_REPO_TMC_OSS}" \
              -DskipTests
  dependency-track:
    executor: java-image
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Install FOSSA CLI
          command: |
            curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - run: mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - run:
          name: Upload to Dependency Track
          command: mvn install
      - run:
          name: Run FOSSA Analysis
          command: |
            fossa analyze \
              --with-telemetry-scope off \
              --endpoint "https://ford.fossa.com/" \
              --project "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" \
              --team "TMC-50844" \
              --policy "Website/Hosted Service Use" \
              --branch "main" \
              --revision "<<pipeline.git.revision>>" \
              --project-url "<<pipeline.project.git_url>>" \
              --project-label "team:telemetry-data" \
              --json
      - run:
          name: Fail build if FOSSA issues
          command: fossa test --with-telemetry-scope off  --endpoint "https://ford.fossa.com/"  --project "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

  private-snapshot-dependency-track:
    executor: snapshot-publisher-image
    working_directory: /root/repo
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Install FOSSA CLI
          command: |
            curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - run:
          name: Run FOSSA Analysis
          command: |
            mvn versions:set -DnewVersion=LATEST-SNAPSHOT -DprocessAllModules
      - run:
          name: Publish tmc-oss-sdk-common-private to au-tmc-snapshots
          command: |
            mvn deploy \
              -Pford-supplier-jfrog-artifactory-snapshots \
              -DaltDeploymentRepository="ford-supplier-jfrog-artifactory-snapshots::${JFROG_URL}/${JFROG_REPO_TMC_OSS}" \
              -DskipTests
      - run:
          name: Run FOSSA Analysis
          command: |
            fossa analyze \
              --with-telemetry-scope off \
              --endpoint "https://ford.fossa.com/" \
              --project "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" \
              --team "TMC-50844" \
              --policy "Website/Hosted Service Use" \
              --branch "<<pipeline.git.branch>>" \
              --revision "<<pipeline.git.revision>>" \
              --project-url "<<pipeline.project.git_url>>" \
              --project-label "team:telemetry-data" \
              --json
      - run:
          name: Fail build if FOSSA issues
          command: fossa test --with-telemetry-scope off  --endpoint "https://ford.fossa.com/"  --project "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
  push-to-public:
    executor: snapshot-publisher-image
    steps:
      - checkout
      - run:
          name: Push to public repo
          command: /root/publish.sh push_public tmc-oss-sdk-common ${CIRCLE_BRANCH} ${CIRCLE_BRANCH}

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - scan_secrets:
          context:
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
      - build:
          requires:
            - scan_secrets
          filters:
            branches:
              # do not build branches which are intended for documentation only
              ignore:
                - /.*docs.*/
                - /.*readme.*/
          context:
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
      - test:
          requires:
            - build
          context:
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
      - private-snapshot-dependency-track:
          context:
            - tmc-cloudsmith-context
            - tmc-oss-context
            - ford-supplier-jfrog-context
          requires:
            - test
          filters:
            branches:
              only: rc
      - private-snapshot-jfrog-dependency-track:
          context:
            - tmc-oss-context
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
          requires:
            - test
          filters:
            branches:
              only: rc
      - push-to-public:
          context:
            - tmc-cloudsmith-context
            - tmc-oss-context
            - ford-supplier-jfrog-context
            - ford-supplier-jfrog-context
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - /release\/.*/

  release:
    jobs:
      #Run Publish on GitHub release
      - scan_secrets:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context:
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - scan_secrets
          context:
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
      - publish-public:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - build
          context:
            - tmc-cloudsmith-context
            - ford-supplier-jfrog-context
      - dependency-track:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - build
          context:
            - tmc-cloudsmith-context
            - tmc-oss-context
            - ford-supplier-jfrog-context
